name: PR CI pre build check

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Surefire already sets spring.profiles.active=test
      - name: Build & Test (H2)
        run: mvn -B -DskipTests=false verify
